[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
turbine_example = "7fH2CnN1qaztG1kr5iWSxJTbYAiLf2ViWgrK1PeJW5kS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://engine.mirror.ad/rpc/c17a132a-b41e-425a-977b-d8fcc4645490"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
